//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 03:56:01 PM IST 
//


package com.cts.homesurveyor.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DriverId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DriverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DriverLicenseNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RelationShipToInsured" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SafeDriverDiscount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Occupation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Operator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LicenseState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}CoverageInfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "driverId",
    "driverName",
    "driverLicenseNo",
    "relationShipToInsured",
    "safeDriverDiscount",
    "occupation",
    "birthDate",
    "age",
    "gender",
    "operator",
    "status",
    "licenseState",
    "coverageInfo"
})
@XmlRootElement(name = "DriverInfo")
public class DriverInfo {

    @XmlElement(name = "DriverId", required = true)
    protected String driverId;
    @XmlElement(name = "DriverName", required = true)
    protected String driverName;
    @XmlElement(name = "DriverLicenseNo", required = true)
    protected String driverLicenseNo;
    @XmlElement(name = "RelationShipToInsured", required = true)
    protected String relationShipToInsured;
    @XmlElement(name = "SafeDriverDiscount", required = true)
    protected String safeDriverDiscount;
    @XmlElement(name = "Occupation", required = true)
    protected String occupation;
    @XmlElement(name = "BirthDate", required = true)
    protected String birthDate;
    @XmlElement(name = "Age", required = true)
    protected String age;
    @XmlElement(name = "Gender", required = true)
    protected String gender;
    @XmlElement(name = "Operator", required = true)
    protected String operator;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "LicenseState", required = true)
    protected String licenseState;
    @XmlElement(name = "CoverageInfo")
    protected List<CoverageInfo> coverageInfo;

    /**
     * Gets the value of the driverId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverId() {
        return driverId;
    }

    /**
     * Sets the value of the driverId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverId(String value) {
        this.driverId = value;
    }

    /**
     * Gets the value of the driverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * Sets the value of the driverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverName(String value) {
        this.driverName = value;
    }

    /**
     * Gets the value of the driverLicenseNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverLicenseNo() {
        return driverLicenseNo;
    }

    /**
     * Sets the value of the driverLicenseNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverLicenseNo(String value) {
        this.driverLicenseNo = value;
    }

    /**
     * Gets the value of the relationShipToInsured property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationShipToInsured() {
        return relationShipToInsured;
    }

    /**
     * Sets the value of the relationShipToInsured property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationShipToInsured(String value) {
        this.relationShipToInsured = value;
    }

    /**
     * Gets the value of the safeDriverDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSafeDriverDiscount() {
        return safeDriverDiscount;
    }

    /**
     * Sets the value of the safeDriverDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSafeDriverDiscount(String value) {
        this.safeDriverDiscount = value;
    }

    /**
     * Gets the value of the occupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * Sets the value of the occupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupation(String value) {
        this.occupation = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAge(String value) {
        this.age = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the licenseState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseState() {
        return licenseState;
    }

    /**
     * Sets the value of the licenseState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseState(String value) {
        this.licenseState = value;
    }

    /**
     * Gets the value of the coverageInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coverageInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoverageInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoverageInfo }
     * 
     * 
     */
    public List<CoverageInfo> getCoverageInfo() {
        if (coverageInfo == null) {
            coverageInfo = new ArrayList<CoverageInfo>();
        }
        return this.coverageInfo;
    }

}
