//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 03:56:01 PM IST 
//


package com.cts.homesurveyor.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PolicyViewAuthority" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ClaimEditAuthority" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "policyViewAuthority",
    "claimEditAuthority"
})
@XmlRootElement(name = "Authority")
public class Authority {

    @XmlElement(name = "PolicyViewAuthority")
    protected boolean policyViewAuthority;
    @XmlElement(name = "ClaimEditAuthority")
    protected boolean claimEditAuthority;

    /**
     * Gets the value of the policyViewAuthority property.
     * 
     */
    public boolean isPolicyViewAuthority() {
        return policyViewAuthority;
    }

    /**
     * Sets the value of the policyViewAuthority property.
     * 
     */
    public void setPolicyViewAuthority(boolean value) {
        this.policyViewAuthority = value;
    }

    /**
     * Gets the value of the claimEditAuthority property.
     * 
     */
    public boolean isClaimEditAuthority() {
        return claimEditAuthority;
    }

    /**
     * Sets the value of the claimEditAuthority property.
     * 
     */
    public void setClaimEditAuthority(boolean value) {
        this.claimEditAuthority = value;
    }

}
