//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 03:56:01 PM IST 
//


package com.cts.homesurveyor.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InjuryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MajorTrauma" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PolicyNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BodyParts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}AddressInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "injuryId",
    "description",
    "majorTrauma",
    "policyNumber",
    "comments",
    "bodyParts",
    "addressInfo"
})
@XmlRootElement(name = "InjuryInfo")
public class InjuryInfo {

    @XmlElement(name = "InjuryId", required = true)
    protected String injuryId;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "MajorTrauma", required = true)
    protected String majorTrauma;
    @XmlElement(name = "PolicyNumber", required = true)
    protected String policyNumber;
    @XmlElement(name = "Comments", required = true)
    protected String comments;
    @XmlElement(name = "BodyParts", required = true)
    protected String bodyParts;
    @XmlElement(name = "AddressInfo")
    protected AddressInfo addressInfo;

    /**
     * Gets the value of the injuryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInjuryId() {
        return injuryId;
    }

    /**
     * Sets the value of the injuryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInjuryId(String value) {
        this.injuryId = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the majorTrauma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMajorTrauma() {
        return majorTrauma;
    }

    /**
     * Sets the value of the majorTrauma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorTrauma(String value) {
        this.majorTrauma = value;
    }

    /**
     * Gets the value of the policyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyNumber() {
        return policyNumber;
    }

    /**
     * Sets the value of the policyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyNumber(String value) {
        this.policyNumber = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the bodyParts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBodyParts() {
        return bodyParts;
    }

    /**
     * Sets the value of the bodyParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBodyParts(String value) {
        this.bodyParts = value;
    }

    /**
     * Gets the value of the addressInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInfo }
     *     
     */
    public AddressInfo getAddressInfo() {
        return addressInfo;
    }

    /**
     * Sets the value of the addressInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInfo }
     *     
     */
    public void setAddressInfo(AddressInfo value) {
        this.addressInfo = value;
    }

}
