//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 03:56:01 PM IST 
//


package com.cts.homesurveyor.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LossHistoryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LossHistoryNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClaimNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StatusCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SourceCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LossDt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LossCauseCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LossAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LossDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PaidAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CarrierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lossHistoryId",
    "lossHistoryNumber",
    "claimNumber",
    "statusCd",
    "sourceCd",
    "lossDt",
    "lossCauseCd",
    "lossAmount",
    "lossDescription",
    "paidAmount",
    "comment",
    "carrierName"
})
@XmlRootElement(name = "LossHistoryInfo")
public class LossHistoryInfo {

    @XmlElement(name = "LossHistoryId", required = true)
    protected String lossHistoryId;
    @XmlElement(name = "LossHistoryNumber", required = true)
    protected String lossHistoryNumber;
    @XmlElement(name = "ClaimNumber", required = true)
    protected String claimNumber;
    @XmlElement(name = "StatusCd", required = true)
    protected String statusCd;
    @XmlElement(name = "SourceCd", required = true)
    protected String sourceCd;
    @XmlElement(name = "LossDt", required = true)
    protected String lossDt;
    @XmlElement(name = "LossCauseCd", required = true)
    protected String lossCauseCd;
    @XmlElement(name = "LossAmount", required = true)
    protected String lossAmount;
    @XmlElement(name = "LossDescription", required = true)
    protected String lossDescription;
    @XmlElement(name = "PaidAmount", required = true)
    protected String paidAmount;
    @XmlElement(name = "Comment", required = true)
    protected String comment;
    @XmlElement(name = "CarrierName", required = true)
    protected String carrierName;

    /**
     * Gets the value of the lossHistoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLossHistoryId() {
        return lossHistoryId;
    }

    /**
     * Sets the value of the lossHistoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLossHistoryId(String value) {
        this.lossHistoryId = value;
    }

    /**
     * Gets the value of the lossHistoryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLossHistoryNumber() {
        return lossHistoryNumber;
    }

    /**
     * Sets the value of the lossHistoryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLossHistoryNumber(String value) {
        this.lossHistoryNumber = value;
    }

    /**
     * Gets the value of the claimNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimNumber() {
        return claimNumber;
    }

    /**
     * Sets the value of the claimNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimNumber(String value) {
        this.claimNumber = value;
    }

    /**
     * Gets the value of the statusCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * Sets the value of the statusCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCd(String value) {
        this.statusCd = value;
    }

    /**
     * Gets the value of the sourceCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceCd() {
        return sourceCd;
    }

    /**
     * Sets the value of the sourceCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceCd(String value) {
        this.sourceCd = value;
    }

    /**
     * Gets the value of the lossDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLossDt() {
        return lossDt;
    }

    /**
     * Sets the value of the lossDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLossDt(String value) {
        this.lossDt = value;
    }

    /**
     * Gets the value of the lossCauseCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLossCauseCd() {
        return lossCauseCd;
    }

    /**
     * Sets the value of the lossCauseCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLossCauseCd(String value) {
        this.lossCauseCd = value;
    }

    /**
     * Gets the value of the lossAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLossAmount() {
        return lossAmount;
    }

    /**
     * Sets the value of the lossAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLossAmount(String value) {
        this.lossAmount = value;
    }

    /**
     * Gets the value of the lossDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLossDescription() {
        return lossDescription;
    }

    /**
     * Sets the value of the lossDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLossDescription(String value) {
        this.lossDescription = value;
    }

    /**
     * Gets the value of the paidAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaidAmount() {
        return paidAmount;
    }

    /**
     * Sets the value of the paidAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaidAmount(String value) {
        this.paidAmount = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the carrierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierName() {
        return carrierName;
    }

    /**
     * Sets the value of the carrierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierName(String value) {
        this.carrierName = value;
    }

}
