//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 03:56:01 PM IST 
//


package com.cts.homesurveyor.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cts.cicsurveyor.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cts.cicsurveyor.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClaimSearchList }
     * 
     */
    public ClaimSearchList createClaimSearchList() {
        return new ClaimSearchList();
    }

    /**
     * Create an instance of {@link VehicleInfo }
     * 
     */
    public VehicleInfo createVehicleInfo() {
        return new VehicleInfo();
    }

    /**
     * Create an instance of {@link AddressInfo }
     * 
     */
    public AddressInfo createAddressInfo() {
        return new AddressInfo();
    }

    /**
     * Create an instance of {@link CoverageInfo }
     * 
     */
    public CoverageInfo createCoverageInfo() {
        return new CoverageInfo();
    }

    /**
     * Create an instance of {@link GetClaimsListRequest }
     * 
     */
    public GetClaimsListRequest createGetClaimsListRequest() {
        return new GetClaimsListRequest();
    }

    /**
     * Create an instance of {@link AuthenticationRequest }
     * 
     */
    public AuthenticationRequest createAuthenticationRequest() {
        return new AuthenticationRequest();
    }

    /**
     * Create an instance of {@link Claim }
     * 
     */
    public Claim createClaim() {
        return new Claim();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link InsuredInfo }
     * 
     */
    public InsuredInfo createInsuredInfo() {
        return new InsuredInfo();
    }

    /**
     * Create an instance of {@link DriverInfo }
     * 
     */
    public DriverInfo createDriverInfo() {
        return new DriverInfo();
    }

    /**
     * Create an instance of {@link LossHistoryInfo }
     * 
     */
    public LossHistoryInfo createLossHistoryInfo() {
        return new LossHistoryInfo();
    }

    /**
     * Create an instance of {@link InjuryInfo }
     * 
     */
    public InjuryInfo createInjuryInfo() {
        return new InjuryInfo();
    }

    /**
     * Create an instance of {@link AuthenticationResponse }
     * 
     */
    public AuthenticationResponse createAuthenticationResponse() {
        return new AuthenticationResponse();
    }

    /**
     * Create an instance of {@link Authority }
     * 
     */
    public Authority createAuthority() {
        return new Authority();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link GetClaimsListResponse }
     * 
     */
    public GetClaimsListResponse createGetClaimsListResponse() {
        return new GetClaimsListResponse();
    }

}
