//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 03:56:01 PM IST 
//


package com.cts.homesurveyor.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClaimId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SurveyorId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClaimNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AtFault" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="InsuredDamageEstimate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="LossDt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportedDt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LossLocationDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}Policy" minOccurs="0"/>
 *         &lt;element ref="{}InjuryInfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "claimId",
    "surveyorId",
    "claimNumber",
    "atFault",
    "insuredDamageEstimate",
    "lossDt",
    "reportedDt",
    "reportedBy",
    "lossLocationDescription",
    "comments",
    "policy",
    "injuryInfo"
})
@XmlRootElement(name = "Claim")
public class Claim {

    @XmlElement(name = "ClaimId", required = true)
    protected String claimId;
    @XmlElement(name = "SurveyorId", required = true)
    protected String surveyorId;
    @XmlElement(name = "ClaimNumber", required = true)
    protected String claimNumber;
    @XmlElement(name = "AtFault")
    protected boolean atFault;
    @XmlElement(name = "InsuredDamageEstimate", required = true)
    protected BigDecimal insuredDamageEstimate;
    @XmlElement(name = "LossDt", required = true)
    protected String lossDt;
    @XmlElement(name = "ReportedDt", required = true)
    protected String reportedDt;
    @XmlElement(name = "ReportedBy", required = true)
    protected String reportedBy;
    @XmlElement(name = "LossLocationDescription", required = true)
    protected String lossLocationDescription;
    @XmlElement(name = "Comments", required = true)
    protected String comments;
    @XmlElement(name = "Policy")
    protected Policy policy;
    @XmlElement(name = "InjuryInfo")
    protected List<InjuryInfo> injuryInfo;

    /**
     * Gets the value of the claimId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimId() {
        return claimId;
    }

    /**
     * Sets the value of the claimId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimId(String value) {
        this.claimId = value;
    }

    /**
     * Gets the value of the surveyorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurveyorId() {
        return surveyorId;
    }

    /**
     * Sets the value of the surveyorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurveyorId(String value) {
        this.surveyorId = value;
    }

    /**
     * Gets the value of the claimNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimNumber() {
        return claimNumber;
    }

    /**
     * Sets the value of the claimNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimNumber(String value) {
        this.claimNumber = value;
    }

    /**
     * Gets the value of the atFault property.
     * 
     */
    public boolean isAtFault() {
        return atFault;
    }

    /**
     * Sets the value of the atFault property.
     * 
     */
    public void setAtFault(boolean value) {
        this.atFault = value;
    }

    /**
     * Gets the value of the insuredDamageEstimate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInsuredDamageEstimate() {
        return insuredDamageEstimate;
    }

    /**
     * Sets the value of the insuredDamageEstimate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInsuredDamageEstimate(BigDecimal value) {
        this.insuredDamageEstimate = value;
    }

    /**
     * Gets the value of the lossDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLossDt() {
        return lossDt;
    }

    /**
     * Sets the value of the lossDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLossDt(String value) {
        this.lossDt = value;
    }

    /**
     * Gets the value of the reportedDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportedDt() {
        return reportedDt;
    }

    /**
     * Sets the value of the reportedDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedDt(String value) {
        this.reportedDt = value;
    }

    /**
     * Gets the value of the reportedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportedBy() {
        return reportedBy;
    }

    /**
     * Sets the value of the reportedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedBy(String value) {
        this.reportedBy = value;
    }

    /**
     * Gets the value of the lossLocationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLossLocationDescription() {
        return lossLocationDescription;
    }

    /**
     * Sets the value of the lossLocationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLossLocationDescription(String value) {
        this.lossLocationDescription = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the policy property.
     * 
     * @return
     *     possible object is
     *     {@link Policy }
     *     
     */
    public Policy getPolicy() {
        return policy;
    }

    /**
     * Sets the value of the policy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Policy }
     *     
     */
    public void setPolicy(Policy value) {
        this.policy = value;
    }

    /**
     * Gets the value of the injuryInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the injuryInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInjuryInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InjuryInfo }
     * 
     * 
     */
    public List<InjuryInfo> getInjuryInfo() {
        if (injuryInfo == null) {
            injuryInfo = new ArrayList<InjuryInfo>();
        }
        return this.injuryInfo;
    }

}
