//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 03:56:01 PM IST 
//


package com.cts.homesurveyor.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VehicleId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Make" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ModelYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VehicleLicenseNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BodyStyle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PerformanceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EngineType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EngineSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EngineHorsePower" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Restraints" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RatingSymbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HasAntiTheftDevice" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="VehicleUse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OwnedBy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EstimatedMileage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegistrationStartDt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegistrationEndDt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}AddressInfo" minOccurs="0"/>
 *         &lt;element ref="{}CoverageInfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vehicleId",
    "make",
    "modelYear",
    "model",
    "vin",
    "vehicleLicenseNo",
    "bodyStyle",
    "performanceCode",
    "engineType",
    "engineSize",
    "engineHorsePower",
    "restraints",
    "ratingSymbol",
    "hasAntiTheftDevice",
    "vehicleUse",
    "ownedBy",
    "estimatedMileage",
    "registrationStartDt",
    "registrationEndDt",
    "addressInfo",
    "coverageInfo"
})
@XmlRootElement(name = "VehicleInfo")
public class VehicleInfo {

    @XmlElement(name = "VehicleId", required = true)
    protected String vehicleId;
    @XmlElement(name = "Make", required = true)
    protected String make;
    @XmlElement(name = "ModelYear", required = true)
    protected String modelYear;
    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "VIN", required = true)
    protected String vin;
    @XmlElement(name = "VehicleLicenseNo", required = true)
    protected String vehicleLicenseNo;
    @XmlElement(name = "BodyStyle", required = true)
    protected String bodyStyle;
    @XmlElement(name = "PerformanceCode", required = true)
    protected String performanceCode;
    @XmlElement(name = "EngineType", required = true)
    protected String engineType;
    @XmlElement(name = "EngineSize", required = true)
    protected String engineSize;
    @XmlElement(name = "EngineHorsePower", required = true)
    protected String engineHorsePower;
    @XmlElement(name = "Restraints", required = true)
    protected String restraints;
    @XmlElement(name = "RatingSymbol", required = true)
    protected String ratingSymbol;
    @XmlElement(name = "HasAntiTheftDevice")
    protected boolean hasAntiTheftDevice;
    @XmlElement(name = "VehicleUse", required = true)
    protected String vehicleUse;
    @XmlElement(name = "OwnedBy", required = true)
    protected String ownedBy;
    @XmlElement(name = "EstimatedMileage", required = true)
    protected String estimatedMileage;
    @XmlElement(name = "RegistrationStartDt", required = true)
    protected String registrationStartDt;
    @XmlElement(name = "RegistrationEndDt", required = true)
    protected String registrationEndDt;
    @XmlElement(name = "AddressInfo")
    protected AddressInfo addressInfo;
    @XmlElement(name = "CoverageInfo")
    protected List<CoverageInfo> coverageInfo;

    /**
     * Gets the value of the vehicleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * Sets the value of the vehicleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleId(String value) {
        this.vehicleId = value;
    }

    /**
     * Gets the value of the make property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMake() {
        return make;
    }

    /**
     * Sets the value of the make property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMake(String value) {
        this.make = value;
    }

    /**
     * Gets the value of the modelYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelYear() {
        return modelYear;
    }

    /**
     * Sets the value of the modelYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelYear(String value) {
        this.modelYear = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the vin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVIN() {
        return vin;
    }

    /**
     * Sets the value of the vin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVIN(String value) {
        this.vin = value;
    }

    /**
     * Gets the value of the vehicleLicenseNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleLicenseNo() {
        return vehicleLicenseNo;
    }

    /**
     * Sets the value of the vehicleLicenseNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleLicenseNo(String value) {
        this.vehicleLicenseNo = value;
    }

    /**
     * Gets the value of the bodyStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBodyStyle() {
        return bodyStyle;
    }

    /**
     * Sets the value of the bodyStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBodyStyle(String value) {
        this.bodyStyle = value;
    }

    /**
     * Gets the value of the performanceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerformanceCode() {
        return performanceCode;
    }

    /**
     * Sets the value of the performanceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerformanceCode(String value) {
        this.performanceCode = value;
    }

    /**
     * Gets the value of the engineType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineType() {
        return engineType;
    }

    /**
     * Sets the value of the engineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineType(String value) {
        this.engineType = value;
    }

    /**
     * Gets the value of the engineSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineSize() {
        return engineSize;
    }

    /**
     * Sets the value of the engineSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineSize(String value) {
        this.engineSize = value;
    }

    /**
     * Gets the value of the engineHorsePower property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineHorsePower() {
        return engineHorsePower;
    }

    /**
     * Sets the value of the engineHorsePower property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineHorsePower(String value) {
        this.engineHorsePower = value;
    }

    /**
     * Gets the value of the restraints property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestraints() {
        return restraints;
    }

    /**
     * Sets the value of the restraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestraints(String value) {
        this.restraints = value;
    }

    /**
     * Gets the value of the ratingSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingSymbol() {
        return ratingSymbol;
    }

    /**
     * Sets the value of the ratingSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingSymbol(String value) {
        this.ratingSymbol = value;
    }

    /**
     * Gets the value of the hasAntiTheftDevice property.
     * 
     */
    public boolean isHasAntiTheftDevice() {
        return hasAntiTheftDevice;
    }

    /**
     * Sets the value of the hasAntiTheftDevice property.
     * 
     */
    public void setHasAntiTheftDevice(boolean value) {
        this.hasAntiTheftDevice = value;
    }

    /**
     * Gets the value of the vehicleUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleUse() {
        return vehicleUse;
    }

    /**
     * Sets the value of the vehicleUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleUse(String value) {
        this.vehicleUse = value;
    }

    /**
     * Gets the value of the ownedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnedBy() {
        return ownedBy;
    }

    /**
     * Sets the value of the ownedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnedBy(String value) {
        this.ownedBy = value;
    }

    /**
     * Gets the value of the estimatedMileage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstimatedMileage() {
        return estimatedMileage;
    }

    /**
     * Sets the value of the estimatedMileage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstimatedMileage(String value) {
        this.estimatedMileage = value;
    }

    /**
     * Gets the value of the registrationStartDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationStartDt() {
        return registrationStartDt;
    }

    /**
     * Sets the value of the registrationStartDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationStartDt(String value) {
        this.registrationStartDt = value;
    }

    /**
     * Gets the value of the registrationEndDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationEndDt() {
        return registrationEndDt;
    }

    /**
     * Sets the value of the registrationEndDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationEndDt(String value) {
        this.registrationEndDt = value;
    }

    /**
     * Gets the value of the addressInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInfo }
     *     
     */
    public AddressInfo getAddressInfo() {
        return addressInfo;
    }

    /**
     * Sets the value of the addressInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInfo }
     *     
     */
    public void setAddressInfo(AddressInfo value) {
        this.addressInfo = value;
    }

    /**
     * Gets the value of the coverageInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coverageInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoverageInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoverageInfo }
     * 
     * 
     */
    public List<CoverageInfo> getCoverageInfo() {
        if (coverageInfo == null) {
            coverageInfo = new ArrayList<CoverageInfo>();
        }
        return this.coverageInfo;
    }

}
